### PR TITLE
Chat implementation(ben/aaron)

### PR DESCRIPTION
**Pull request by aaronma2**
Implemented main chat classes

### CODE REVIEW

**Review by VivianLiu2357 — DISMISSED** [review]
Code organization and practice: 
- full CLEAN structure with good organization
- overall nice naming, but some could be more informative (i.e. 'm' for ChatLogRequestModel is probably it bit too brief)
- for the interface methods, the 'public' keyword is not necessary, you can delete them :))
- 'Override' header in implementing class methods are not necessary
- some of the attributes can be made final
- coding style is consistent and relatively easy to read

Tests: missing, please make more tests to aim for full coverage

Documentation: please document your code to explain (javadoc and line comments are fine, but try to keep it clear and concise)

Functionality: code looks like it works, will test it out after I pull code

Relatively CLEAN and SOLID

**Review by adityabandekar — DISMISSED** [review]
Overall: Good use of CLEAN architecture and SOLID principles. Everything follows the dependency inversion rules and CLEAN layers. We should add a comment at the top of each class to indicate which CLEAN layer the class is in. Also we need to add more documentation.

ChatDsGateway: We should store the chats in CSV files to save the chats when the program closes. We should throw helpful exceptions instead of returning null to help with debugging if this case ever occurs. We should have better and longer variable names than single letter variable names, to make it more clear what each variable represents. Also there should be more descriptive comments instead of "todo: what if chat already exists? too bad!" because currently it is not clear what actually happens when chat exists. Furthermore, when "todo" is in a comment, it should be uppercase as "TODO" in order to get IntellIJ to mark it as TODO.

ChatInteractor: Perfect.
ChatPresenter: Perfect.
ChatDsBoundary: Perfect.
ChatInputBoundary: Perfect.
ChatOutputBoundary: Perfect.

ChatCreationRequestModel: We should create getters in order to get each of the users separately.

ChatDataRecieveModel:  Should be refractored to be "ChatDataReceiveModel" instead of "ChatDataRecieveModel" because it is spelled "Receive". To be consistent with camelCase, chat_exists should be renamed to chatExists.

ChatLogRequestModel: Same comment as ChatCreationRequestModel.

ChatSendMessageModel: Perfect.

Chat: We have an entity also named "Chat". To refractor we should rename one.

ChatMessage: Perfect.

**Review by laciscat — DISMISSED** [review]
Good job on implementing CLEAN architecture in your code. Remember to use javadoc for comments to make code easier to follow along. I realized that your "todo" comments are not recognized by Intellij. Please change these comments to "TODO".

Functionality of all the code their style looks good. 
Please implement the changes Aditya suggested as I agree with them.

**Review by VivianLiu2357 — APPROVED** [review]
Code organization:
-

**Review by zipstyx — APPROVED** [review]

**Review by adityabandekar — APPROVED** [review]

**Pull request merged**
